import 'package:flutter_gen/gen_l10n/app_localizations.dart';

extension AppLocalizationsExt on AppLocalizations {
  String getLocalizedSurahName(String surahKey) {
    switch (surahKey) {
      case "Al-Fatiha":
        return one;
      case "Al-Baqarah":
        return two;
      case "Aal-E-Imran":
        return three;
      case "An-Nisa":
        return four;
      case "Al-Maidah":
        return five;
      case "Al-An'am":
        return six;
      case "Al-A'raf":
        return seven;
      case "Al-Anfal":
        return eight;
      case "At-Tawbah":
        return nine;
      case "Yunus":
        return ten;
      case "Hud":
        return eleven;
      case "Yusuf":
        return twelve;
      case "Ar-Ra'd":
        return thirteen;
      case "Ibrahim":
        return fourteen;
      case "Al-Hijr":
        return fifteen;
      case "An-Nahl":
        return sixteen;
      case "Al-Isra":
        return seventeen;
      case "Al-Kahf":
        return eighteen;
      case "Maryam":
        return nineteen;
      case "Taha":
        return twenty;
      case "Al-Anbiya":
        return twentyone;
      case "Al-Hajj":
        return twentytwo;
      case "Al-Mu’minun":
        return twentythree;
      case "An-Nur":
        return twentyfour;
      case "Al-Furqan":
        return twentyfive;
      case "Ash-Shu'ara":
        return twentysix;
      case "An-Naml":
        return twentyseven;
      case "Al-Qasas":
        return twentyeight;
      case "Al-Ankabut":
        return twentynine;
      case "Ar-Rum":
        return thirty;
      case "Luqman":
        return thirtyone;
      case "As-Sajda":
        return thirtytwo;
      case "Al-Ahzab":
        return thirtythree;
      case "Saba":
        return thirtyfour;
      case "Fatir":
        return thirtyfive;
      case "Ya-Sin":
        return thirtysix;
      case "As-Saffat":
        return thirtyseven;
      case "Sad":
        return thirtyeight;
      case "Az-Zumar":
        return thirtynine;
      case "Ghafir":
        return forty;
      case "Fussilat":
        return fortyone;
      case "Ash-Shura":
        return fortytwo;
      case "Az-Zukhruf":
        return fortythree;
      case "Ad-Dukhan":
        return fortyfour;
      case "Al-Jathiya":
        return fortyfive;
      case "Al-Ahqaf":
        return fortysix;
      case "Muhammad":
        return fortyseven;
      case "Al-Fath":
        return fortyeight;
      case "Al-Hujurat":
        return fortynine;
      case "Qaf":
        return fifty;
      case "Adh-Dhariyat":
        return fiftyone;
      case "At-Tur":
        return fiftytwo;
      case "An-Najm":
        return fiftythree;
      case "Al-Qamar":
        return fiftyfour;
      case "Ar-Rahman":
        return fiftyfive;
      case "Al-Waqi'a":
        return fiftysix;
      case "Al-Hadid":
        return fiftyseven;
      case "Al-Mujadila":
        return fiftyeight;
      case "Al-Hashr":
        return fiftynine;
      case "Al-Mumtahina":
        return sixty;
      case "As-Saff":
        return sixtyone;
      case "Al-Jumu'a":
        return sixtytwo;
      case "Al-Munafiqun":
        return sixtythree;
      case "At-Taghabun":
        return sixtyfour;
      case "At-Talaq":
        return sixtyfive;
      case "At-Tahrim":
        return sixtysix;
      case "Al-Mulk":
        return sixtyseven;
      case "Al-Qalam":
        return sixtyeight;
      case "Al-Haqqah":
        return sixtynine;
      case "Al-Ma'arij":
        return seventy;
      case "Nuh":
        return seventyone;
      case "Al-Jinn":
        return seventytwo;
      case "Al-Muzzammil":
        return seventythree;
      case "Al-Muddathir":
        return seventyfour;
      case "Al-Qiyamah":
        return seventyfive;
      case "Al-Insan":
        return seventysix;
      case "Al-Mursalat":
        return seventyseven;
      case "An-Naba":
        return seventyeight;
      case "An-Nazi'at":
        return seventynine;
      case "Abasa":
        return eighty;
      case "At-Takwir":
        return eightyone;
      case "Al-Infitar":
        return eightytwo;
      case "Al-Mutaffifin":
        return eightythree;
      case "Al-Inshiqaq":
        return eightyfour;
      case "Al-Buruj":
        return eightyfive;
      case "At-Tariq":
        return eightysix;
      case "Al-A'la":
        return eightyseven;
      case "Al-Ghashiya":
        return eightyeight;
      case "Al-Fajr":
        return eightynine;
      case "Al-Balad":
        return ninety;
      case "Ash-Shams":
        return ninetyone;
      case "Al-Lail":
        return ninetytwo;
      case "Ad-Duha":
        return ninetythree;
      case "Ash-Sharh":
        return ninetyfour;
      case "At-Tin":
        return ninetyfive;
      case "Al-Alaq":
        return ninetysix;
      case "Al-Qadr":
        return ninetyseven;
      case "Al-Bayyina":
        return ninetyeight;
      case "Az-Zalzala":
        return ninetynine;
      case "Al-Adiyat":
        return onehundred;
      case "Al-Qari'a":
        return onehundredone;
      case "At-Takathur":
        return onehundredtwo;
      case "Al-Asr":
        return onehundredthree;
      case "Al-Humaza":
        return onehundredfour;
      case "Al-Fil":
        return onehundredfive;
      case "Quraish":
        return onehundredsix;
      case "Al-Ma'un":
        return onehundredseven;
      case "Al-Kawthar":
        return onehundredeight;
      case "Al-Kafirun":
        return onehundrednine;
      case "An-Nasr":
        return onehundredten;
      case "Al-Masad":
        return onehundredeleven;
      case "Al-Ikhlas":
        return onehundredtwelve;
      case "Al-Falaq":
        return onehundredthirteen;
      case "An-Nas":
        return onehundredfourteen;
      default:
        return surahKey;
    }
  }
}
